title: Patrick Calorio Carvalho
author: Patrick Calorio Carvalho
description: Transmita o que aprendeu. Força, mestria. Mas fraqueza, insensatez, fracasso também. Sim, fracasso acima de tudo. O maior professor, o fracasso é - Mestre Yoda
keywords: Blog, Jekyll, Patrick Calorio Carvalho,Desenvolvimento, Programação, Tecnologia, Python, JavaScript, HTML, CSS, GitHub, Git, Open Source
baseurl: ""
url: ""
